### PR TITLE
Refactoring + Memory improvements

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
I refactored the code a little :)
* Fixed your copyright headers
* The LICENSE is now included in your jar.
* Explicitly declare the visibility of fields
* Calculator is no longer static
* Seperated Metrics into their own dedicated class

This is still a draft, some things will still be changed before this is ready.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
I am gonna delay the asynchronous feature a bit.
But I did improve your memory usage by changing the List into a Map and reducing redundant calls/entries.

**Comment by Seggan** [comment]
Do ya mind testing out the reinforced alloy calculation for your pr and giving the results? I'm interested to see if the bug is fixed.

**Comment by Seggan** [comment]
If I try calculating it spams "You are not a player!"

**Comment by TheBusyBiscuit** [comment]
Fixed.

34885fb0203df5a29075ec52334896f2

**Comment by TheBusyBiscuit** [comment]
As a little bonus: Thought it would be nice to order the ingredients in ascending order ;)

**Review by Seggan — APPROVED** [review]

**Pull request merged**
